version: "3"
services:
  app:
    build: ./app
    image: setup-ltr:1.0
    environment:
      - ES_HOST=es
      - ES_PORT=9200
    depends_on:
      - es
    networks:
      - es-net
    volumes:
      - ./app/demo:/work/demo
  es:
    build: ./es
    image: es-ltr:1.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    networks:
      - es-net
  cerebro:
    image: lmenezes/cerebro:0.8.3
    ports:
      - 9000:9000
    depends_on:
      - es
    networks:
      - es-net

networks:
  es-net:
