version: "3"
services:
  app:
    build: ./app
    image: ltr-demo:1.0
    environment:
      - ES_HOST=es
      - ES_PORT=9200
    depends_on:
      - es
    networks:
      - es-net
  es:
    build: ./es
    image: es-ltr:1.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    networks:
      - es-net

networks:
  es-net:
